#ifndef BLINKLIB_CONFIG_H_
#define BLINKLIB_CONFIG_H_

#define BGA_CUSTOM_BLINKLIB_IR_DATAGRAM_LEN 4
#define BGA_CUSTOM_BLINKLIB_SEND_PROBE_TIMEOUT_MS 300
#define BGA_CUSTOM_BLINKLIB_FACE_EXPIRATION_TIMEOUT_MS 350

#endif  // BLINKLIB_CONFIG_H_