#ifndef BROADCAST_CONFIG_H_
#define BROADCAST_CONFIG_H_

#define BROADCAST_MESSAGE_PAYLOAD_BYTES 3
#define BROADCAST_DISABLE_REPLIES
#define BROADCAST_ENABLE_MESSAGE_HANDLER

#endif  // BROADCAST_CONFIG_H_